FROM mcr.microsoft.com/devcontainers/rust:0-1-bullseye

# Include lld linker to improve build times either by using environment variable
# RUSTFLAGS="-C link-arg=-fuse-ld=lld" or with Cargo's configuration file (i.e see .cargo/config.toml).
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install clang lld nodejs npm default-mysql-client \
    && apt-get autoremove -y \
    && apt-get clean -y

# Add nightly for more stable Leptops integration
RUN rustup toolchain install nightly \
    && rustup default nightly \
    && rustup target add wasm32-unknown-unknown

# Add the leptos CLIm, sqlx, and other dependencies
RUN cargo install cargo-leptos \
    && cargo install cargo-generate \
    && cargo install sqlx-cli --no-default-features --features native-tls,mysql

# Grab the pscale CLI
ARG PSCALE_VERSION=0.125.0
ARG PSCALE_DEB=pscale_${PSCALE_VERSION}_linux_amd64.deb
ARG PSCALE_DEB_URL=https://github.com/planetscale/cli/releases/download/v${PSCALE_VERSION}/pscale_${PSCALE_VERSION}_linux_amd64.deb

RUN sudo wget ${PSCALE_DEB_URL} \
    && sudo dpkg -i ${PSCALE_DEB} \
    && rm -f ${PSCALE_DEB}
