name: Deploy docs

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install mdbook
        run: cargo install mdbook

      - name: Build docs
        run: mdbook build
        working-directory: docs

      - name: Publish to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs/book --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
